db:
  host: "![VGAw0q8TX81rH/Pnbo8hvtYgULuUDWCmDBD+WWtaBQE=]"
  port: "![dMvpeAkbuFaTAkNFb+RW0/vzRs7BgUJfZTJxhfsbgBU=]"
  password: "![X1xexWqIcbqg6XWwWyVOghHIzyqRH1p5hRqJGCcx0mA=]"
  user: "![dC0S4t8F6FjnlsepOqNpUxLUOEvGJq4M2ymD6/xrVdI=]"
  database: "![nz8ebVnd8M2u1l+/Q38+o+izsInUY15nhhJJYCIU9Cc=]"
